spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-third-party

server:
  port: 30000


