server:
  port: 11000

spring:
  datasource:
    url: jdbc:mysql://59.110.150.246/gulimall-wms
    username: shi
    password: Shiduichen123@
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-ware
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH-mm-ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.atguigu: debug
